### ISSUE TITLE
Can't launch soulride

### ISSUE THREAD

**Issue by realitix** [Echelon9/soulride#58]
Hello Rhys,
I tried your game on Linux but when I launch `./soulride`, I get:

```
Can't open mountain data file 'Mammoth.srt' for input.
```

Maybe I did something wrong.

**Comment by Echelon9** [comment]
Hello @realitix thanks for your interest in Soul Ride.

The engine is freely available under the GPL, however the game assets (maps/mountains etc) are not, so I can't redistribute them with the engine source code.

However, the original developer Slingshot did make certain mountains available as demos from their website, of which Jay Peak is the best example.

If you download the Linux version from [here](http://soulride.com/products/jay_peak.html) you need only to copy the folder named `Jay_Peak` into the top level of your local engine and then run `./start_Jay_Peak.sh`. The engine executable from the Slingshot download can be deleted, as you'd prefer to use the latest engine that you built with `make`.

Other configuration options can be found at https://github.com/Echelon9/soulride/blob/master/docs/Configuration.md

**Comment by realitix** [comment]
It works
